using System.IO;
using System;

namespace Csweb
{
    internal class Writer
    {
        string autoMessage => "<!-- Generated by CSWeb - https://github.com/PixelatedLagg/CSWeb-lib -->";
        //called once and only if there is nothing on the file
        internal void Write(string path)
        {
            if (!Common.ValidPath(path, autoMessage))
            {
                throw new ArgumentException("Not a valid file path!");
            }
        }
    }
}